@echo Running tests...
vendor/bin/phpunit.bat

@echo Ensuring PHP version compatibility...
vendor/bin/phpcs.bat -p --runtime-set testVersion 5.5- --standard=vendor/phpcompatibility/php-compatibility/PHPCompatibility --extensions=php --ignore=/vendor .